"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class LicenseType(metaclass=_LicenseType):
    V = typing.NewType('V', builtins.int)

global___LicenseType = LicenseType

ZERO = LicenseType.V(0)
DEFAULT = LicenseType.V(1)
OFFLINE = LicenseType.V(2)

class _LicenseType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[LicenseType.V], builtins.type):  # type: ignore
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    ZERO = LicenseType.V(0)
    DEFAULT = LicenseType.V(1)
    OFFLINE = LicenseType.V(2)

class ProtocolVersion(metaclass=_ProtocolVersion):
    V = typing.NewType('V', builtins.int)

global___ProtocolVersion = ProtocolVersion

VERSION_2_0 = ProtocolVersion.V(20)
VERSION_2_1 = ProtocolVersion.V(21)

class _ProtocolVersion(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ProtocolVersion.V], builtins.type):  # type: ignore
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    VERSION_2_0 = ProtocolVersion.V(20)
    VERSION_2_1 = ProtocolVersion.V(21)

class ClientIdentification(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class TokenType(metaclass=_TokenType):
        V = typing.NewType('V', builtins.int)

    KEYBOX = ClientIdentification.TokenType.V(0)
    DEVICE_CERTIFICATE = ClientIdentification.TokenType.V(1)
    REMOTE_ATTESTATION_CERTIFICATE = ClientIdentification.TokenType.V(2)

    class _TokenType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[TokenType.V], builtins.type):  # type: ignore
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        KEYBOX = ClientIdentification.TokenType.V(0)
        DEVICE_CERTIFICATE = ClientIdentification.TokenType.V(1)
        REMOTE_ATTESTATION_CERTIFICATE = ClientIdentification.TokenType.V(2)

    class NameValue(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        NAME_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        Name: typing.Text = ...
        Value: typing.Text = ...

        def __init__(self,
            *,
            Name : typing.Optional[typing.Text] = ...,
            Value : typing.Optional[typing.Text] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal[u"Name",b"Name",u"Value",b"Value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"Name",b"Name",u"Value",b"Value"]) -> None: ...

    class ClientCapabilities(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        class HdcpVersion(metaclass=_HdcpVersion):
            V = typing.NewType('V', builtins.int)

        HDCP_NONE = ClientIdentification.ClientCapabilities.HdcpVersion.V(0)
        HDCP_V1 = ClientIdentification.ClientCapabilities.HdcpVersion.V(1)
        HDCP_V2 = ClientIdentification.ClientCapabilities.HdcpVersion.V(2)
        HDCP_V2_1 = ClientIdentification.ClientCapabilities.HdcpVersion.V(3)
        HDCP_V2_2 = ClientIdentification.ClientCapabilities.HdcpVersion.V(4)

        class _HdcpVersion(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[HdcpVersion.V], builtins.type):  # type: ignore
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
            HDCP_NONE = ClientIdentification.ClientCapabilities.HdcpVersion.V(0)
            HDCP_V1 = ClientIdentification.ClientCapabilities.HdcpVersion.V(1)
            HDCP_V2 = ClientIdentification.ClientCapabilities.HdcpVersion.V(2)
            HDCP_V2_1 = ClientIdentification.ClientCapabilities.HdcpVersion.V(3)
            HDCP_V2_2 = ClientIdentification.ClientCapabilities.HdcpVersion.V(4)

        class CertificateKeyType(metaclass=_CertificateKeyType):
            V = typing.NewType('V', builtins.int)

        RSA_2048 = ClientIdentification.ClientCapabilities.CertificateKeyType.V(0)
        RSA_3072 = ClientIdentification.ClientCapabilities.CertificateKeyType.V(1)

        class _CertificateKeyType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[CertificateKeyType.V], builtins.type):  # type: ignore
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
            RSA_2048 = ClientIdentification.ClientCapabilities.CertificateKeyType.V(0)
            RSA_3072 = ClientIdentification.ClientCapabilities.CertificateKeyType.V(1)

        CLIENTTOKEN_FIELD_NUMBER: builtins.int
        SESSIONTOKEN_FIELD_NUMBER: builtins.int
        VIDEORESOLUTIONCONSTRAINTS_FIELD_NUMBER: builtins.int
        MAXHDCPVERSION_FIELD_NUMBER: builtins.int
        OEMCRYPTOAPIVERSION_FIELD_NUMBER: builtins.int
        ANTIROLLBACKUSAGETABLE_FIELD_NUMBER: builtins.int
        SRMVERSION_FIELD_NUMBER: builtins.int
        CANUPDATESRM_FIELD_NUMBER: builtins.int
        SUPPORTEDCERTIFICATEKEYTYPE_FIELD_NUMBER: builtins.int
        ClientToken: builtins.int = ...
        SessionToken: builtins.int = ...
        VideoResolutionConstraints: builtins.int = ...
        MaxHdcpVersion: global___ClientIdentification.ClientCapabilities.HdcpVersion.V = ...
        OemCryptoApiVersion: builtins.int = ...
        AntiRollbackUsageTable: builtins.int = ...
        SrmVersion: builtins.int = ...
        CanUpdateSrm: builtins.bool = ...

        @property
        def SupportedCertificateKeyType(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___ClientIdentification.ClientCapabilities.CertificateKeyType.V]: ...

        def __init__(self,
            *,
            ClientToken : typing.Optional[builtins.int] = ...,
            SessionToken : typing.Optional[builtins.int] = ...,
            VideoResolutionConstraints : typing.Optional[builtins.int] = ...,
            MaxHdcpVersion : typing.Optional[global___ClientIdentification.ClientCapabilities.HdcpVersion.V] = ...,
            OemCryptoApiVersion : typing.Optional[builtins.int] = ...,
            AntiRollbackUsageTable : typing.Optional[builtins.int] = ...,
            SrmVersion : typing.Optional[builtins.int] = ...,
            CanUpdateSrm : typing.Optional[builtins.bool] = ...,
            SupportedCertificateKeyType : typing.Optional[typing.Iterable[global___ClientIdentification.ClientCapabilities.CertificateKeyType.V]] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal[u"AntiRollbackUsageTable",b"AntiRollbackUsageTable",u"CanUpdateSrm",b"CanUpdateSrm",u"ClientToken",b"ClientToken",u"MaxHdcpVersion",b"MaxHdcpVersion",u"OemCryptoApiVersion",b"OemCryptoApiVersion",u"SessionToken",b"SessionToken",u"SrmVersion",b"SrmVersion",u"VideoResolutionConstraints",b"VideoResolutionConstraints"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"AntiRollbackUsageTable",b"AntiRollbackUsageTable",u"CanUpdateSrm",b"CanUpdateSrm",u"ClientToken",b"ClientToken",u"MaxHdcpVersion",b"MaxHdcpVersion",u"OemCryptoApiVersion",b"OemCryptoApiVersion",u"SessionToken",b"SessionToken",u"SrmVersion",b"SrmVersion",u"SupportedCertificateKeyType",b"SupportedCertificateKeyType",u"VideoResolutionConstraints",b"VideoResolutionConstraints"]) -> None: ...

    TYPE_FIELD_NUMBER: builtins.int
    TOKEN_FIELD_NUMBER: builtins.int
    CLIENTINFO_FIELD_NUMBER: builtins.int
    PROVIDERCLIENTTOKEN_FIELD_NUMBER: builtins.int
    LICENSECOUNTER_FIELD_NUMBER: builtins.int
    _CLIENTCAPABILITIES_FIELD_NUMBER: builtins.int
    _FILEHASHES_FIELD_NUMBER: builtins.int
    Type: global___ClientIdentification.TokenType.V = ...
    ProviderClientToken: builtins.bytes = ...
    LicenseCounter: builtins.int = ...

    @property
    def Token(self) -> global___SignedDeviceCertificate: ...

    @property
    def ClientInfo(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ClientIdentification.NameValue]: ...

    @property
    def _ClientCapabilities(self) -> global___ClientIdentification.ClientCapabilities: ...

    @property
    def _FileHashes(self) -> global___FileHashes: ...

    def __init__(self,
        *,
        Type : typing.Optional[global___ClientIdentification.TokenType.V] = ...,
        Token : typing.Optional[global___SignedDeviceCertificate] = ...,
        ClientInfo : typing.Optional[typing.Iterable[global___ClientIdentification.NameValue]] = ...,
        ProviderClientToken : typing.Optional[builtins.bytes] = ...,
        LicenseCounter : typing.Optional[builtins.int] = ...,
        _ClientCapabilities : typing.Optional[global___ClientIdentification.ClientCapabilities] = ...,
        _FileHashes : typing.Optional[global___FileHashes] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"LicenseCounter",b"LicenseCounter",u"ProviderClientToken",b"ProviderClientToken",u"Token",b"Token",u"Type",b"Type",u"_ClientCapabilities",b"_ClientCapabilities",u"_FileHashes",b"_FileHashes"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"ClientInfo",b"ClientInfo",u"LicenseCounter",b"LicenseCounter",u"ProviderClientToken",b"ProviderClientToken",u"Token",b"Token",u"Type",b"Type",u"_ClientCapabilities",b"_ClientCapabilities",u"_FileHashes",b"_FileHashes"]) -> None: ...
global___ClientIdentification = ClientIdentification

class ClientIdentificationRaw(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class TokenType(metaclass=_TokenType):
        V = typing.NewType('V', builtins.int)

    KEYBOX = ClientIdentificationRaw.TokenType.V(0)
    DEVICE_CERTIFICATE = ClientIdentificationRaw.TokenType.V(1)
    REMOTE_ATTESTATION_CERTIFICATE = ClientIdentificationRaw.TokenType.V(2)

    class _TokenType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[TokenType.V], builtins.type):  # type: ignore
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        KEYBOX = ClientIdentificationRaw.TokenType.V(0)
        DEVICE_CERTIFICATE = ClientIdentificationRaw.TokenType.V(1)
        REMOTE_ATTESTATION_CERTIFICATE = ClientIdentificationRaw.TokenType.V(2)

    class NameValue(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        NAME_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        Name: typing.Text = ...
        Value: typing.Text = ...

        def __init__(self,
            *,
            Name : typing.Optional[typing.Text] = ...,
            Value : typing.Optional[typing.Text] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal[u"Name",b"Name",u"Value",b"Value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"Name",b"Name",u"Value",b"Value"]) -> None: ...

    class ClientCapabilities(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        class HdcpVersion(metaclass=_HdcpVersion):
            V = typing.NewType('V', builtins.int)

        HDCP_NONE = ClientIdentificationRaw.ClientCapabilities.HdcpVersion.V(0)
        HDCP_V1 = ClientIdentificationRaw.ClientCapabilities.HdcpVersion.V(1)
        HDCP_V2 = ClientIdentificationRaw.ClientCapabilities.HdcpVersion.V(2)
        HDCP_V2_1 = ClientIdentificationRaw.ClientCapabilities.HdcpVersion.V(3)
        HDCP_V2_2 = ClientIdentificationRaw.ClientCapabilities.HdcpVersion.V(4)

        class _HdcpVersion(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[HdcpVersion.V], builtins.type):  # type: ignore
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
            HDCP_NONE = ClientIdentificationRaw.ClientCapabilities.HdcpVersion.V(0)
            HDCP_V1 = ClientIdentificationRaw.ClientCapabilities.HdcpVersion.V(1)
            HDCP_V2 = ClientIdentificationRaw.ClientCapabilities.HdcpVersion.V(2)
            HDCP_V2_1 = ClientIdentificationRaw.ClientCapabilities.HdcpVersion.V(3)
            HDCP_V2_2 = ClientIdentificationRaw.ClientCapabilities.HdcpVersion.V(4)

        class CertificateKeyType(metaclass=_CertificateKeyType):
            V = typing.NewType('V', builtins.int)

        RSA_2048 = ClientIdentificationRaw.ClientCapabilities.CertificateKeyType.V(0)
        RSA_3072 = ClientIdentificationRaw.ClientCapabilities.CertificateKeyType.V(1)

        class _CertificateKeyType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[CertificateKeyType.V], builtins.type):  # type: ignore
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
            RSA_2048 = ClientIdentificationRaw.ClientCapabilities.CertificateKeyType.V(0)
            RSA_3072 = ClientIdentificationRaw.ClientCapabilities.CertificateKeyType.V(1)

        CLIENTTOKEN_FIELD_NUMBER: builtins.int
        SESSIONTOKEN_FIELD_NUMBER: builtins.int
        VIDEORESOLUTIONCONSTRAINTS_FIELD_NUMBER: builtins.int
        MAXHDCPVERSION_FIELD_NUMBER: builtins.int
        OEMCRYPTOAPIVERSION_FIELD_NUMBER: builtins.int
        ANTIROLLBACKUSAGETABLE_FIELD_NUMBER: builtins.int
        SRMVERSION_FIELD_NUMBER: builtins.int
        CANUPDATESRM_FIELD_NUMBER: builtins.int
        SUPPORTEDCERTIFICATEKEYTYPE_FIELD_NUMBER: builtins.int
        ClientToken: builtins.int = ...
        SessionToken: builtins.int = ...
        VideoResolutionConstraints: builtins.int = ...
        MaxHdcpVersion: global___ClientIdentificationRaw.ClientCapabilities.HdcpVersion.V = ...
        OemCryptoApiVersion: builtins.int = ...
        AntiRollbackUsageTable: builtins.int = ...
        SrmVersion: builtins.int = ...
        CanUpdateSrm: builtins.bool = ...

        @property
        def SupportedCertificateKeyType(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___ClientIdentificationRaw.ClientCapabilities.CertificateKeyType.V]: ...

        def __init__(self,
            *,
            ClientToken : typing.Optional[builtins.int] = ...,
            SessionToken : typing.Optional[builtins.int] = ...,
            VideoResolutionConstraints : typing.Optional[builtins.int] = ...,
            MaxHdcpVersion : typing.Optional[global___ClientIdentificationRaw.ClientCapabilities.HdcpVersion.V] = ...,
            OemCryptoApiVersion : typing.Optional[builtins.int] = ...,
            AntiRollbackUsageTable : typing.Optional[builtins.int] = ...,
            SrmVersion : typing.Optional[builtins.int] = ...,
            CanUpdateSrm : typing.Optional[builtins.bool] = ...,
            SupportedCertificateKeyType : typing.Optional[typing.Iterable[global___ClientIdentificationRaw.ClientCapabilities.CertificateKeyType.V]] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal[u"AntiRollbackUsageTable",b"AntiRollbackUsageTable",u"CanUpdateSrm",b"CanUpdateSrm",u"ClientToken",b"ClientToken",u"MaxHdcpVersion",b"MaxHdcpVersion",u"OemCryptoApiVersion",b"OemCryptoApiVersion",u"SessionToken",b"SessionToken",u"SrmVersion",b"SrmVersion",u"VideoResolutionConstraints",b"VideoResolutionConstraints"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"AntiRollbackUsageTable",b"AntiRollbackUsageTable",u"CanUpdateSrm",b"CanUpdateSrm",u"ClientToken",b"ClientToken",u"MaxHdcpVersion",b"MaxHdcpVersion",u"OemCryptoApiVersion",b"OemCryptoApiVersion",u"SessionToken",b"SessionToken",u"SrmVersion",b"SrmVersion",u"SupportedCertificateKeyType",b"SupportedCertificateKeyType",u"VideoResolutionConstraints",b"VideoResolutionConstraints"]) -> None: ...

    TYPE_FIELD_NUMBER: builtins.int
    TOKEN_FIELD_NUMBER: builtins.int
    CLIENTINFO_FIELD_NUMBER: builtins.int
    PROVIDERCLIENTTOKEN_FIELD_NUMBER: builtins.int
    LICENSECOUNTER_FIELD_NUMBER: builtins.int
    _CLIENTCAPABILITIES_FIELD_NUMBER: builtins.int
    _FILEHASHES_FIELD_NUMBER: builtins.int
    Type: global___ClientIdentificationRaw.TokenType.V = ...
    Token: builtins.bytes = ...
    ProviderClientToken: builtins.bytes = ...
    LicenseCounter: builtins.int = ...

    @property
    def ClientInfo(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ClientIdentificationRaw.NameValue]: ...

    @property
    def _ClientCapabilities(self) -> global___ClientIdentificationRaw.ClientCapabilities: ...

    @property
    def _FileHashes(self) -> global___FileHashes: ...

    def __init__(self,
        *,
        Type : typing.Optional[global___ClientIdentificationRaw.TokenType.V] = ...,
        Token : typing.Optional[builtins.bytes] = ...,
        ClientInfo : typing.Optional[typing.Iterable[global___ClientIdentificationRaw.NameValue]] = ...,
        ProviderClientToken : typing.Optional[builtins.bytes] = ...,
        LicenseCounter : typing.Optional[builtins.int] = ...,
        _ClientCapabilities : typing.Optional[global___ClientIdentificationRaw.ClientCapabilities] = ...,
        _FileHashes : typing.Optional[global___FileHashes] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"LicenseCounter",b"LicenseCounter",u"ProviderClientToken",b"ProviderClientToken",u"Token",b"Token",u"Type",b"Type",u"_ClientCapabilities",b"_ClientCapabilities",u"_FileHashes",b"_FileHashes"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"ClientInfo",b"ClientInfo",u"LicenseCounter",b"LicenseCounter",u"ProviderClientToken",b"ProviderClientToken",u"Token",b"Token",u"Type",b"Type",u"_ClientCapabilities",b"_ClientCapabilities",u"_FileHashes",b"_FileHashes"]) -> None: ...
global___ClientIdentificationRaw = ClientIdentificationRaw

class DeviceCertificate(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class CertificateType(metaclass=_CertificateType):
        V = typing.NewType('V', builtins.int)

    ROOT = DeviceCertificate.CertificateType.V(0)
    INTERMEDIATE = DeviceCertificate.CertificateType.V(1)
    USER_DEVICE = DeviceCertificate.CertificateType.V(2)
    SERVICE = DeviceCertificate.CertificateType.V(3)

    class _CertificateType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[CertificateType.V], builtins.type):  # type: ignore
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        ROOT = DeviceCertificate.CertificateType.V(0)
        INTERMEDIATE = DeviceCertificate.CertificateType.V(1)
        USER_DEVICE = DeviceCertificate.CertificateType.V(2)
        SERVICE = DeviceCertificate.CertificateType.V(3)

    TYPE_FIELD_NUMBER: builtins.int
    SERIALNUMBER_FIELD_NUMBER: builtins.int
    CREATIONTIMESECONDS_FIELD_NUMBER: builtins.int
    PUBLICKEY_FIELD_NUMBER: builtins.int
    SYSTEMID_FIELD_NUMBER: builtins.int
    TESTDEVICEDEPRECATED_FIELD_NUMBER: builtins.int
    SERVICEID_FIELD_NUMBER: builtins.int
    Type: global___DeviceCertificate.CertificateType.V = ...
    SerialNumber: builtins.bytes = ...
    CreationTimeSeconds: builtins.int = ...
    PublicKey: builtins.bytes = ...
    SystemId: builtins.int = ...
    TestDeviceDeprecated: builtins.int = ...
    ServiceId: builtins.bytes = ...

    def __init__(self,
        *,
        Type : typing.Optional[global___DeviceCertificate.CertificateType.V] = ...,
        SerialNumber : typing.Optional[builtins.bytes] = ...,
        CreationTimeSeconds : typing.Optional[builtins.int] = ...,
        PublicKey : typing.Optional[builtins.bytes] = ...,
        SystemId : typing.Optional[builtins.int] = ...,
        TestDeviceDeprecated : typing.Optional[builtins.int] = ...,
        ServiceId : typing.Optional[builtins.bytes] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"CreationTimeSeconds",b"CreationTimeSeconds",u"PublicKey",b"PublicKey",u"SerialNumber",b"SerialNumber",u"ServiceId",b"ServiceId",u"SystemId",b"SystemId",u"TestDeviceDeprecated",b"TestDeviceDeprecated",u"Type",b"Type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"CreationTimeSeconds",b"CreationTimeSeconds",u"PublicKey",b"PublicKey",u"SerialNumber",b"SerialNumber",u"ServiceId",b"ServiceId",u"SystemId",b"SystemId",u"TestDeviceDeprecated",b"TestDeviceDeprecated",u"Type",b"Type"]) -> None: ...
global___DeviceCertificate = DeviceCertificate

class DeviceCertificateStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class CertificateStatus(metaclass=_CertificateStatus):
        V = typing.NewType('V', builtins.int)

    VALID = DeviceCertificateStatus.CertificateStatus.V(0)
    REVOKED = DeviceCertificateStatus.CertificateStatus.V(1)

    class _CertificateStatus(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[CertificateStatus.V], builtins.type):  # type: ignore
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        VALID = DeviceCertificateStatus.CertificateStatus.V(0)
        REVOKED = DeviceCertificateStatus.CertificateStatus.V(1)

    SERIALNUMBER_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    DEVICEINFO_FIELD_NUMBER: builtins.int
    SerialNumber: builtins.bytes = ...
    Status: global___DeviceCertificateStatus.CertificateStatus.V = ...

    @property
    def DeviceInfo(self) -> global___ProvisionedDeviceInfo: ...

    def __init__(self,
        *,
        SerialNumber : typing.Optional[builtins.bytes] = ...,
        Status : typing.Optional[global___DeviceCertificateStatus.CertificateStatus.V] = ...,
        DeviceInfo : typing.Optional[global___ProvisionedDeviceInfo] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"DeviceInfo",b"DeviceInfo",u"SerialNumber",b"SerialNumber",u"Status",b"Status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"DeviceInfo",b"DeviceInfo",u"SerialNumber",b"SerialNumber",u"Status",b"Status"]) -> None: ...
global___DeviceCertificateStatus = DeviceCertificateStatus

class DeviceCertificateStatusList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    CREATIONTIMESECONDS_FIELD_NUMBER: builtins.int
    CERTIFICATESTATUS_FIELD_NUMBER: builtins.int
    CreationTimeSeconds: builtins.int = ...

    @property
    def CertificateStatus(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DeviceCertificateStatus]: ...

    def __init__(self,
        *,
        CreationTimeSeconds : typing.Optional[builtins.int] = ...,
        CertificateStatus : typing.Optional[typing.Iterable[global___DeviceCertificateStatus]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"CreationTimeSeconds",b"CreationTimeSeconds"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"CertificateStatus",b"CertificateStatus",u"CreationTimeSeconds",b"CreationTimeSeconds"]) -> None: ...
global___DeviceCertificateStatusList = DeviceCertificateStatusList

class EncryptedClientIdentification(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SERVICEID_FIELD_NUMBER: builtins.int
    SERVICECERTIFICATESERIALNUMBER_FIELD_NUMBER: builtins.int
    ENCRYPTEDCLIENTID_FIELD_NUMBER: builtins.int
    ENCRYPTEDCLIENTIDIV_FIELD_NUMBER: builtins.int
    ENCRYPTEDPRIVACYKEY_FIELD_NUMBER: builtins.int
    ServiceId: typing.Text = ...
    ServiceCertificateSerialNumber: builtins.bytes = ...
    EncryptedClientId: builtins.bytes = ...
    EncryptedClientIdIv: builtins.bytes = ...
    EncryptedPrivacyKey: builtins.bytes = ...

    def __init__(self,
        *,
        ServiceId : typing.Optional[typing.Text] = ...,
        ServiceCertificateSerialNumber : typing.Optional[builtins.bytes] = ...,
        EncryptedClientId : typing.Optional[builtins.bytes] = ...,
        EncryptedClientIdIv : typing.Optional[builtins.bytes] = ...,
        EncryptedPrivacyKey : typing.Optional[builtins.bytes] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"EncryptedClientId",b"EncryptedClientId",u"EncryptedClientIdIv",b"EncryptedClientIdIv",u"EncryptedPrivacyKey",b"EncryptedPrivacyKey",u"ServiceCertificateSerialNumber",b"ServiceCertificateSerialNumber",u"ServiceId",b"ServiceId"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"EncryptedClientId",b"EncryptedClientId",u"EncryptedClientIdIv",b"EncryptedClientIdIv",u"EncryptedPrivacyKey",b"EncryptedPrivacyKey",u"ServiceCertificateSerialNumber",b"ServiceCertificateSerialNumber",u"ServiceId",b"ServiceId"]) -> None: ...
global___EncryptedClientIdentification = EncryptedClientIdentification

class LicenseIdentification(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    REQUESTID_FIELD_NUMBER: builtins.int
    SESSIONID_FIELD_NUMBER: builtins.int
    PURCHASEID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    PROVIDERSESSIONTOKEN_FIELD_NUMBER: builtins.int
    RequestId: builtins.bytes = ...
    SessionId: builtins.bytes = ...
    PurchaseId: builtins.bytes = ...
    Type: global___LicenseType.V = ...
    Version: builtins.int = ...
    ProviderSessionToken: builtins.bytes = ...

    def __init__(self,
        *,
        RequestId : typing.Optional[builtins.bytes] = ...,
        SessionId : typing.Optional[builtins.bytes] = ...,
        PurchaseId : typing.Optional[builtins.bytes] = ...,
        Type : typing.Optional[global___LicenseType.V] = ...,
        Version : typing.Optional[builtins.int] = ...,
        ProviderSessionToken : typing.Optional[builtins.bytes] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"ProviderSessionToken",b"ProviderSessionToken",u"PurchaseId",b"PurchaseId",u"RequestId",b"RequestId",u"SessionId",b"SessionId",u"Type",b"Type",u"Version",b"Version"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"ProviderSessionToken",b"ProviderSessionToken",u"PurchaseId",b"PurchaseId",u"RequestId",b"RequestId",u"SessionId",b"SessionId",u"Type",b"Type",u"Version",b"Version"]) -> None: ...
global___LicenseIdentification = LicenseIdentification

class License(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class Policy(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        CANPLAY_FIELD_NUMBER: builtins.int
        CANPERSIST_FIELD_NUMBER: builtins.int
        CANRENEW_FIELD_NUMBER: builtins.int
        RENTALDURATIONSECONDS_FIELD_NUMBER: builtins.int
        PLAYBACKDURATIONSECONDS_FIELD_NUMBER: builtins.int
        LICENSEDURATIONSECONDS_FIELD_NUMBER: builtins.int
        RENEWALRECOVERYDURATIONSECONDS_FIELD_NUMBER: builtins.int
        RENEWALSERVERURL_FIELD_NUMBER: builtins.int
        RENEWALDELAYSECONDS_FIELD_NUMBER: builtins.int
        RENEWALRETRYINTERVALSECONDS_FIELD_NUMBER: builtins.int
        RENEWWITHUSAGE_FIELD_NUMBER: builtins.int
        CanPlay: builtins.bool = ...
        CanPersist: builtins.bool = ...
        CanRenew: builtins.bool = ...
        RentalDurationSeconds: builtins.int = ...
        PlaybackDurationSeconds: builtins.int = ...
        LicenseDurationSeconds: builtins.int = ...
        RenewalRecoveryDurationSeconds: builtins.int = ...
        RenewalServerUrl: typing.Text = ...
        RenewalDelaySeconds: builtins.int = ...
        RenewalRetryIntervalSeconds: builtins.int = ...
        RenewWithUsage: builtins.bool = ...

        def __init__(self,
            *,
            CanPlay : typing.Optional[builtins.bool] = ...,
            CanPersist : typing.Optional[builtins.bool] = ...,
            CanRenew : typing.Optional[builtins.bool] = ...,
            RentalDurationSeconds : typing.Optional[builtins.int] = ...,
            PlaybackDurationSeconds : typing.Optional[builtins.int] = ...,
            LicenseDurationSeconds : typing.Optional[builtins.int] = ...,
            RenewalRecoveryDurationSeconds : typing.Optional[builtins.int] = ...,
            RenewalServerUrl : typing.Optional[typing.Text] = ...,
            RenewalDelaySeconds : typing.Optional[builtins.int] = ...,
            RenewalRetryIntervalSeconds : typing.Optional[builtins.int] = ...,
            RenewWithUsage : typing.Optional[builtins.bool] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal[u"CanPersist",b"CanPersist",u"CanPlay",b"CanPlay",u"CanRenew",b"CanRenew",u"LicenseDurationSeconds",b"LicenseDurationSeconds",u"PlaybackDurationSeconds",b"PlaybackDurationSeconds",u"RenewWithUsage",b"RenewWithUsage",u"RenewalDelaySeconds",b"RenewalDelaySeconds",u"RenewalRecoveryDurationSeconds",b"RenewalRecoveryDurationSeconds",u"RenewalRetryIntervalSeconds",b"RenewalRetryIntervalSeconds",u"RenewalServerUrl",b"RenewalServerUrl",u"RentalDurationSeconds",b"RentalDurationSeconds"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"CanPersist",b"CanPersist",u"CanPlay",b"CanPlay",u"CanRenew",b"CanRenew",u"LicenseDurationSeconds",b"LicenseDurationSeconds",u"PlaybackDurationSeconds",b"PlaybackDurationSeconds",u"RenewWithUsage",b"RenewWithUsage",u"RenewalDelaySeconds",b"RenewalDelaySeconds",u"RenewalRecoveryDurationSeconds",b"RenewalRecoveryDurationSeconds",u"RenewalRetryIntervalSeconds",b"RenewalRetryIntervalSeconds",u"RenewalServerUrl",b"RenewalServerUrl",u"RentalDurationSeconds",b"RentalDurationSeconds"]) -> None: ...

    class KeyContainer(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        class KeyType(metaclass=_KeyType):
            V = typing.NewType('V', builtins.int)

        SIGNING = License.KeyContainer.KeyType.V(1)
        CONTENT = License.KeyContainer.KeyType.V(2)
        KEY_CONTROL = License.KeyContainer.KeyType.V(3)
        OPERATOR_SESSION = License.KeyContainer.KeyType.V(4)

        class _KeyType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[KeyType.V], builtins.type):  # type: ignore
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
            SIGNING = License.KeyContainer.KeyType.V(1)
            CONTENT = License.KeyContainer.KeyType.V(2)
            KEY_CONTROL = License.KeyContainer.KeyType.V(3)
            OPERATOR_SESSION = License.KeyContainer.KeyType.V(4)

        class SecurityLevel(metaclass=_SecurityLevel):
            V = typing.NewType('V', builtins.int)

        SW_SECURE_CRYPTO = License.KeyContainer.SecurityLevel.V(1)
        SW_SECURE_DECODE = License.KeyContainer.SecurityLevel.V(2)
        HW_SECURE_CRYPTO = License.KeyContainer.SecurityLevel.V(3)
        HW_SECURE_DECODE = License.KeyContainer.SecurityLevel.V(4)
        HW_SECURE_ALL = License.KeyContainer.SecurityLevel.V(5)

        class _SecurityLevel(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[SecurityLevel.V], builtins.type):  # type: ignore
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
            SW_SECURE_CRYPTO = License.KeyContainer.SecurityLevel.V(1)
            SW_SECURE_DECODE = License.KeyContainer.SecurityLevel.V(2)
            HW_SECURE_CRYPTO = License.KeyContainer.SecurityLevel.V(3)
            HW_SECURE_DECODE = License.KeyContainer.SecurityLevel.V(4)
            HW_SECURE_ALL = License.KeyContainer.SecurityLevel.V(5)

        class OutputProtection(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
            class CGMS(metaclass=_CGMS):
                V = typing.NewType('V', builtins.int)

            COPY_FREE = License.KeyContainer.OutputProtection.CGMS.V(0)
            COPY_ONCE = License.KeyContainer.OutputProtection.CGMS.V(2)
            COPY_NEVER = License.KeyContainer.OutputProtection.CGMS.V(3)
            CGMS_NONE = License.KeyContainer.OutputProtection.CGMS.V(42)

            class _CGMS(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[CGMS.V], builtins.type):  # type: ignore
                DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
                COPY_FREE = License.KeyContainer.OutputProtection.CGMS.V(0)
                COPY_ONCE = License.KeyContainer.OutputProtection.CGMS.V(2)
                COPY_NEVER = License.KeyContainer.OutputProtection.CGMS.V(3)
                CGMS_NONE = License.KeyContainer.OutputProtection.CGMS.V(42)

            HDCP_FIELD_NUMBER: builtins.int
            CGMSFLAGS_FIELD_NUMBER: builtins.int
            Hdcp: global___ClientIdentification.ClientCapabilities.HdcpVersion.V = ...
            CgmsFlags: global___License.KeyContainer.OutputProtection.CGMS.V = ...

            def __init__(self,
                *,
                Hdcp : typing.Optional[global___ClientIdentification.ClientCapabilities.HdcpVersion.V] = ...,
                CgmsFlags : typing.Optional[global___License.KeyContainer.OutputProtection.CGMS.V] = ...,
                ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal[u"CgmsFlags",b"CgmsFlags",u"Hdcp",b"Hdcp"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal[u"CgmsFlags",b"CgmsFlags",u"Hdcp",b"Hdcp"]) -> None: ...

        class KeyControl(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
            KEYCONTROLBLOCK_FIELD_NUMBER: builtins.int
            IV_FIELD_NUMBER: builtins.int
            KeyControlBlock: builtins.bytes = ...
            Iv: builtins.bytes = ...

            def __init__(self,
                *,
                KeyControlBlock : typing.Optional[builtins.bytes] = ...,
                Iv : typing.Optional[builtins.bytes] = ...,
                ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal[u"Iv",b"Iv",u"KeyControlBlock",b"KeyControlBlock"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal[u"Iv",b"Iv",u"KeyControlBlock",b"KeyControlBlock"]) -> None: ...

        class OperatorSessionKeyPermissions(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
            ALLOWENCRYPT_FIELD_NUMBER: builtins.int
            ALLOWDECRYPT_FIELD_NUMBER: builtins.int
            ALLOWSIGN_FIELD_NUMBER: builtins.int
            ALLOWSIGNATUREVERIFY_FIELD_NUMBER: builtins.int
            AllowEncrypt: builtins.int = ...
            AllowDecrypt: builtins.int = ...
            AllowSign: builtins.int = ...
            AllowSignatureVerify: builtins.int = ...

            def __init__(self,
                *,
                AllowEncrypt : typing.Optional[builtins.int] = ...,
                AllowDecrypt : typing.Optional[builtins.int] = ...,
                AllowSign : typing.Optional[builtins.int] = ...,
                AllowSignatureVerify : typing.Optional[builtins.int] = ...,
                ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal[u"AllowDecrypt",b"AllowDecrypt",u"AllowEncrypt",b"AllowEncrypt",u"AllowSign",b"AllowSign",u"AllowSignatureVerify",b"AllowSignatureVerify"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal[u"AllowDecrypt",b"AllowDecrypt",u"AllowEncrypt",b"AllowEncrypt",u"AllowSign",b"AllowSign",u"AllowSignatureVerify",b"AllowSignatureVerify"]) -> None: ...

        class VideoResolutionConstraint(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
            MINRESOLUTIONPIXELS_FIELD_NUMBER: builtins.int
            MAXRESOLUTIONPIXELS_FIELD_NUMBER: builtins.int
            REQUIREDPROTECTION_FIELD_NUMBER: builtins.int
            MinResolutionPixels: builtins.int = ...
            MaxResolutionPixels: builtins.int = ...

            @property
            def RequiredProtection(self) -> global___License.KeyContainer.OutputProtection: ...

            def __init__(self,
                *,
                MinResolutionPixels : typing.Optional[builtins.int] = ...,
                MaxResolutionPixels : typing.Optional[builtins.int] = ...,
                RequiredProtection : typing.Optional[global___License.KeyContainer.OutputProtection] = ...,
                ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal[u"MaxResolutionPixels",b"MaxResolutionPixels",u"MinResolutionPixels",b"MinResolutionPixels",u"RequiredProtection",b"RequiredProtection"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal[u"MaxResolutionPixels",b"MaxResolutionPixels",u"MinResolutionPixels",b"MinResolutionPixels",u"RequiredProtection",b"RequiredProtection"]) -> None: ...

        ID_FIELD_NUMBER: builtins.int
        IV_FIELD_NUMBER: builtins.int
        KEY_FIELD_NUMBER: builtins.int
        TYPE_FIELD_NUMBER: builtins.int
        LEVEL_FIELD_NUMBER: builtins.int
        REQUIREDPROTECTION_FIELD_NUMBER: builtins.int
        REQUESTEDPROTECTION_FIELD_NUMBER: builtins.int
        _KEYCONTROL_FIELD_NUMBER: builtins.int
        _OPERATORSESSIONKEYPERMISSIONS_FIELD_NUMBER: builtins.int
        VIDEORESOLUTIONCONSTRAINTS_FIELD_NUMBER: builtins.int
        Id: builtins.bytes = ...
        Iv: builtins.bytes = ...
        Key: builtins.bytes = ...
        Type: global___License.KeyContainer.KeyType.V = ...
        Level: global___License.KeyContainer.SecurityLevel.V = ...

        @property
        def RequiredProtection(self) -> global___License.KeyContainer.OutputProtection: ...

        @property
        def RequestedProtection(self) -> global___License.KeyContainer.OutputProtection: ...

        @property
        def _KeyControl(self) -> global___License.KeyContainer.KeyControl: ...

        @property
        def _OperatorSessionKeyPermissions(self) -> global___License.KeyContainer.OperatorSessionKeyPermissions: ...

        @property
        def VideoResolutionConstraints(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___License.KeyContainer.VideoResolutionConstraint]: ...

        def __init__(self,
            *,
            Id : typing.Optional[builtins.bytes] = ...,
            Iv : typing.Optional[builtins.bytes] = ...,
            Key : typing.Optional[builtins.bytes] = ...,
            Type : typing.Optional[global___License.KeyContainer.KeyType.V] = ...,
            Level : typing.Optional[global___License.KeyContainer.SecurityLevel.V] = ...,
            RequiredProtection : typing.Optional[global___License.KeyContainer.OutputProtection] = ...,
            RequestedProtection : typing.Optional[global___License.KeyContainer.OutputProtection] = ...,
            _KeyControl : typing.Optional[global___License.KeyContainer.KeyControl] = ...,
            _OperatorSessionKeyPermissions : typing.Optional[global___License.KeyContainer.OperatorSessionKeyPermissions] = ...,
            VideoResolutionConstraints : typing.Optional[typing.Iterable[global___License.KeyContainer.VideoResolutionConstraint]] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal[u"Id",b"Id",u"Iv",b"Iv",u"Key",b"Key",u"Level",b"Level",u"RequestedProtection",b"RequestedProtection",u"RequiredProtection",b"RequiredProtection",u"Type",b"Type",u"_KeyControl",b"_KeyControl",u"_OperatorSessionKeyPermissions",b"_OperatorSessionKeyPermissions"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"Id",b"Id",u"Iv",b"Iv",u"Key",b"Key",u"Level",b"Level",u"RequestedProtection",b"RequestedProtection",u"RequiredProtection",b"RequiredProtection",u"Type",b"Type",u"VideoResolutionConstraints",b"VideoResolutionConstraints",u"_KeyControl",b"_KeyControl",u"_OperatorSessionKeyPermissions",b"_OperatorSessionKeyPermissions"]) -> None: ...

    ID_FIELD_NUMBER: builtins.int
    _POLICY_FIELD_NUMBER: builtins.int
    KEY_FIELD_NUMBER: builtins.int
    LICENSESTARTTIME_FIELD_NUMBER: builtins.int
    REMOTEATTESTATIONVERIFIED_FIELD_NUMBER: builtins.int
    PROVIDERCLIENTTOKEN_FIELD_NUMBER: builtins.int
    PROTECTIONSCHEME_FIELD_NUMBER: builtins.int
    LicenseStartTime: builtins.int = ...
    RemoteAttestationVerified: builtins.int = ...
    ProviderClientToken: builtins.bytes = ...
    ProtectionScheme: builtins.int = ...

    @property
    def Id(self) -> global___LicenseIdentification: ...

    @property
    def _Policy(self) -> global___License.Policy: ...

    @property
    def Key(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___License.KeyContainer]: ...

    def __init__(self,
        *,
        Id : typing.Optional[global___LicenseIdentification] = ...,
        _Policy : typing.Optional[global___License.Policy] = ...,
        Key : typing.Optional[typing.Iterable[global___License.KeyContainer]] = ...,
        LicenseStartTime : typing.Optional[builtins.int] = ...,
        RemoteAttestationVerified : typing.Optional[builtins.int] = ...,
        ProviderClientToken : typing.Optional[builtins.bytes] = ...,
        ProtectionScheme : typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"Id",b"Id",u"LicenseStartTime",b"LicenseStartTime",u"ProtectionScheme",b"ProtectionScheme",u"ProviderClientToken",b"ProviderClientToken",u"RemoteAttestationVerified",b"RemoteAttestationVerified",u"_Policy",b"_Policy"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"Id",b"Id",u"Key",b"Key",u"LicenseStartTime",b"LicenseStartTime",u"ProtectionScheme",b"ProtectionScheme",u"ProviderClientToken",b"ProviderClientToken",u"RemoteAttestationVerified",b"RemoteAttestationVerified",u"_Policy",b"_Policy"]) -> None: ...
global___License = License

class LicenseError(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class Error(metaclass=_Error):
        V = typing.NewType('V', builtins.int)

    INVALID_DEVICE_CERTIFICATE = LicenseError.Error.V(1)
    REVOKED_DEVICE_CERTIFICATE = LicenseError.Error.V(2)
    SERVICE_UNAVAILABLE = LicenseError.Error.V(3)

    class _Error(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Error.V], builtins.type):  # type: ignore
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        INVALID_DEVICE_CERTIFICATE = LicenseError.Error.V(1)
        REVOKED_DEVICE_CERTIFICATE = LicenseError.Error.V(2)
        SERVICE_UNAVAILABLE = LicenseError.Error.V(3)

    ERRORCODE_FIELD_NUMBER: builtins.int
    ErrorCode: global___LicenseError.Error.V = ...

    def __init__(self,
        *,
        ErrorCode : typing.Optional[global___LicenseError.Error.V] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"ErrorCode",b"ErrorCode"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"ErrorCode",b"ErrorCode"]) -> None: ...
global___LicenseError = LicenseError

class LicenseRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class RequestType(metaclass=_RequestType):
        V = typing.NewType('V', builtins.int)

    NEW = LicenseRequest.RequestType.V(1)
    RENEWAL = LicenseRequest.RequestType.V(2)
    RELEASE = LicenseRequest.RequestType.V(3)

    class _RequestType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[RequestType.V], builtins.type):  # type: ignore
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        NEW = LicenseRequest.RequestType.V(1)
        RENEWAL = LicenseRequest.RequestType.V(2)
        RELEASE = LicenseRequest.RequestType.V(3)

    class ContentIdentification(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        class CENC(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
            PSSH_FIELD_NUMBER: builtins.int
            LICENSETYPE_FIELD_NUMBER: builtins.int
            REQUESTID_FIELD_NUMBER: builtins.int
            LicenseType: global___LicenseType.V = ...
            RequestId: builtins.bytes = ...

            @property
            def Pssh(self) -> global___WidevineCencHeader: ...

            def __init__(self,
                *,
                Pssh : typing.Optional[global___WidevineCencHeader] = ...,
                LicenseType : typing.Optional[global___LicenseType.V] = ...,
                RequestId : typing.Optional[builtins.bytes] = ...,
                ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal[u"LicenseType",b"LicenseType",u"Pssh",b"Pssh",u"RequestId",b"RequestId"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal[u"LicenseType",b"LicenseType",u"Pssh",b"Pssh",u"RequestId",b"RequestId"]) -> None: ...

        class WebM(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
            HEADER_FIELD_NUMBER: builtins.int
            LICENSETYPE_FIELD_NUMBER: builtins.int
            REQUESTID_FIELD_NUMBER: builtins.int
            Header: builtins.bytes = ...
            LicenseType: global___LicenseType.V = ...
            RequestId: builtins.bytes = ...

            def __init__(self,
                *,
                Header : typing.Optional[builtins.bytes] = ...,
                LicenseType : typing.Optional[global___LicenseType.V] = ...,
                RequestId : typing.Optional[builtins.bytes] = ...,
                ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal[u"Header",b"Header",u"LicenseType",b"LicenseType",u"RequestId",b"RequestId"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal[u"Header",b"Header",u"LicenseType",b"LicenseType",u"RequestId",b"RequestId"]) -> None: ...

        class ExistingLicense(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
            LICENSEID_FIELD_NUMBER: builtins.int
            SECONDSSINCESTARTED_FIELD_NUMBER: builtins.int
            SECONDSSINCELASTPLAYED_FIELD_NUMBER: builtins.int
            SESSIONUSAGETABLEENTRY_FIELD_NUMBER: builtins.int
            SecondsSinceStarted: builtins.int = ...
            SecondsSinceLastPlayed: builtins.int = ...
            SessionUsageTableEntry: builtins.bytes = ...

            @property
            def LicenseId(self) -> global___LicenseIdentification: ...

            def __init__(self,
                *,
                LicenseId : typing.Optional[global___LicenseIdentification] = ...,
                SecondsSinceStarted : typing.Optional[builtins.int] = ...,
                SecondsSinceLastPlayed : typing.Optional[builtins.int] = ...,
                SessionUsageTableEntry : typing.Optional[builtins.bytes] = ...,
                ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal[u"LicenseId",b"LicenseId",u"SecondsSinceLastPlayed",b"SecondsSinceLastPlayed",u"SecondsSinceStarted",b"SecondsSinceStarted",u"SessionUsageTableEntry",b"SessionUsageTableEntry"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal[u"LicenseId",b"LicenseId",u"SecondsSinceLastPlayed",b"SecondsSinceLastPlayed",u"SecondsSinceStarted",b"SecondsSinceStarted",u"SessionUsageTableEntry",b"SessionUsageTableEntry"]) -> None: ...

        CENCID_FIELD_NUMBER: builtins.int
        WEBMID_FIELD_NUMBER: builtins.int
        LICENSE_FIELD_NUMBER: builtins.int

        @property
        def CencId(self) -> global___LicenseRequest.ContentIdentification.CENC: ...

        @property
        def WebmId(self) -> global___LicenseRequest.ContentIdentification.WebM: ...

        @property
        def License(self) -> global___LicenseRequest.ContentIdentification.ExistingLicense: ...

        def __init__(self,
            *,
            CencId : typing.Optional[global___LicenseRequest.ContentIdentification.CENC] = ...,
            WebmId : typing.Optional[global___LicenseRequest.ContentIdentification.WebM] = ...,
            License : typing.Optional[global___LicenseRequest.ContentIdentification.ExistingLicense] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal[u"CencId",b"CencId",u"License",b"License",u"WebmId",b"WebmId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"CencId",b"CencId",u"License",b"License",u"WebmId",b"WebmId"]) -> None: ...

    CLIENTID_FIELD_NUMBER: builtins.int
    CONTENTID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    REQUESTTIME_FIELD_NUMBER: builtins.int
    KEYCONTROLNONCEDEPRECATED_FIELD_NUMBER: builtins.int
    PROTOCOLVERSION_FIELD_NUMBER: builtins.int
    KEYCONTROLNONCE_FIELD_NUMBER: builtins.int
    ENCRYPTEDCLIENTID_FIELD_NUMBER: builtins.int
    Type: global___LicenseRequest.RequestType.V = ...
    RequestTime: builtins.int = ...
    KeyControlNonceDeprecated: builtins.bytes = ...
    ProtocolVersion: global___ProtocolVersion.V = ...
    KeyControlNonce: builtins.int = ...

    @property
    def ClientId(self) -> global___ClientIdentification: ...

    @property
    def ContentId(self) -> global___LicenseRequest.ContentIdentification: ...

    @property
    def EncryptedClientId(self) -> global___EncryptedClientIdentification: ...

    def __init__(self,
        *,
        ClientId : typing.Optional[global___ClientIdentification] = ...,
        ContentId : typing.Optional[global___LicenseRequest.ContentIdentification] = ...,
        Type : typing.Optional[global___LicenseRequest.RequestType.V] = ...,
        RequestTime : typing.Optional[builtins.int] = ...,
        KeyControlNonceDeprecated : typing.Optional[builtins.bytes] = ...,
        ProtocolVersion : typing.Optional[global___ProtocolVersion.V] = ...,
        KeyControlNonce : typing.Optional[builtins.int] = ...,
        EncryptedClientId : typing.Optional[global___EncryptedClientIdentification] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"ClientId",b"ClientId",u"ContentId",b"ContentId",u"EncryptedClientId",b"EncryptedClientId",u"KeyControlNonce",b"KeyControlNonce",u"KeyControlNonceDeprecated",b"KeyControlNonceDeprecated",u"ProtocolVersion",b"ProtocolVersion",u"RequestTime",b"RequestTime",u"Type",b"Type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"ClientId",b"ClientId",u"ContentId",b"ContentId",u"EncryptedClientId",b"EncryptedClientId",u"KeyControlNonce",b"KeyControlNonce",u"KeyControlNonceDeprecated",b"KeyControlNonceDeprecated",u"ProtocolVersion",b"ProtocolVersion",u"RequestTime",b"RequestTime",u"Type",b"Type"]) -> None: ...
global___LicenseRequest = LicenseRequest

class LicenseRequestRaw(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class RequestType(metaclass=_RequestType):
        V = typing.NewType('V', builtins.int)

    NEW = LicenseRequestRaw.RequestType.V(1)
    RENEWAL = LicenseRequestRaw.RequestType.V(2)
    RELEASE = LicenseRequestRaw.RequestType.V(3)

    class _RequestType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[RequestType.V], builtins.type):  # type: ignore
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        NEW = LicenseRequestRaw.RequestType.V(1)
        RENEWAL = LicenseRequestRaw.RequestType.V(2)
        RELEASE = LicenseRequestRaw.RequestType.V(3)

    class ContentIdentification(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        class CENC(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
            PSSH_FIELD_NUMBER: builtins.int
            LICENSETYPE_FIELD_NUMBER: builtins.int
            REQUESTID_FIELD_NUMBER: builtins.int
            Pssh: builtins.bytes = ...
            LicenseType: global___LicenseType.V = ...
            RequestId: builtins.bytes = ...

            def __init__(self,
                *,
                Pssh : typing.Optional[builtins.bytes] = ...,
                LicenseType : typing.Optional[global___LicenseType.V] = ...,
                RequestId : typing.Optional[builtins.bytes] = ...,
                ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal[u"LicenseType",b"LicenseType",u"Pssh",b"Pssh",u"RequestId",b"RequestId"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal[u"LicenseType",b"LicenseType",u"Pssh",b"Pssh",u"RequestId",b"RequestId"]) -> None: ...

        class WebM(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
            HEADER_FIELD_NUMBER: builtins.int
            LICENSETYPE_FIELD_NUMBER: builtins.int
            REQUESTID_FIELD_NUMBER: builtins.int
            Header: builtins.bytes = ...
            LicenseType: global___LicenseType.V = ...
            RequestId: builtins.bytes = ...

            def __init__(self,
                *,
                Header : typing.Optional[builtins.bytes] = ...,
                LicenseType : typing.Optional[global___LicenseType.V] = ...,
                RequestId : typing.Optional[builtins.bytes] = ...,
                ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal[u"Header",b"Header",u"LicenseType",b"LicenseType",u"RequestId",b"RequestId"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal[u"Header",b"Header",u"LicenseType",b"LicenseType",u"RequestId",b"RequestId"]) -> None: ...

        class ExistingLicense(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
            LICENSEID_FIELD_NUMBER: builtins.int
            SECONDSSINCESTARTED_FIELD_NUMBER: builtins.int
            SECONDSSINCELASTPLAYED_FIELD_NUMBER: builtins.int
            SESSIONUSAGETABLEENTRY_FIELD_NUMBER: builtins.int
            SecondsSinceStarted: builtins.int = ...
            SecondsSinceLastPlayed: builtins.int = ...
            SessionUsageTableEntry: builtins.bytes = ...

            @property
            def LicenseId(self) -> global___LicenseIdentification: ...

            def __init__(self,
                *,
                LicenseId : typing.Optional[global___LicenseIdentification] = ...,
                SecondsSinceStarted : typing.Optional[builtins.int] = ...,
                SecondsSinceLastPlayed : typing.Optional[builtins.int] = ...,
                SessionUsageTableEntry : typing.Optional[builtins.bytes] = ...,
                ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal[u"LicenseId",b"LicenseId",u"SecondsSinceLastPlayed",b"SecondsSinceLastPlayed",u"SecondsSinceStarted",b"SecondsSinceStarted",u"SessionUsageTableEntry",b"SessionUsageTableEntry"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal[u"LicenseId",b"LicenseId",u"SecondsSinceLastPlayed",b"SecondsSinceLastPlayed",u"SecondsSinceStarted",b"SecondsSinceStarted",u"SessionUsageTableEntry",b"SessionUsageTableEntry"]) -> None: ...

        CENCID_FIELD_NUMBER: builtins.int
        WEBMID_FIELD_NUMBER: builtins.int
        LICENSE_FIELD_NUMBER: builtins.int

        @property
        def CencId(self) -> global___LicenseRequestRaw.ContentIdentification.CENC: ...

        @property
        def WebmId(self) -> global___LicenseRequestRaw.ContentIdentification.WebM: ...

        @property
        def License(self) -> global___LicenseRequestRaw.ContentIdentification.ExistingLicense: ...

        def __init__(self,
            *,
            CencId : typing.Optional[global___LicenseRequestRaw.ContentIdentification.CENC] = ...,
            WebmId : typing.Optional[global___LicenseRequestRaw.ContentIdentification.WebM] = ...,
            License : typing.Optional[global___LicenseRequestRaw.ContentIdentification.ExistingLicense] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal[u"CencId",b"CencId",u"License",b"License",u"WebmId",b"WebmId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"CencId",b"CencId",u"License",b"License",u"WebmId",b"WebmId"]) -> None: ...

    CLIENTID_FIELD_NUMBER: builtins.int
    CONTENTID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    REQUESTTIME_FIELD_NUMBER: builtins.int
    KEYCONTROLNONCEDEPRECATED_FIELD_NUMBER: builtins.int
    PROTOCOLVERSION_FIELD_NUMBER: builtins.int
    KEYCONTROLNONCE_FIELD_NUMBER: builtins.int
    ENCRYPTEDCLIENTID_FIELD_NUMBER: builtins.int
    Type: global___LicenseRequestRaw.RequestType.V = ...
    RequestTime: builtins.int = ...
    KeyControlNonceDeprecated: builtins.bytes = ...
    ProtocolVersion: global___ProtocolVersion.V = ...
    KeyControlNonce: builtins.int = ...

    @property
    def ClientId(self) -> global___ClientIdentification: ...

    @property
    def ContentId(self) -> global___LicenseRequestRaw.ContentIdentification: ...

    @property
    def EncryptedClientId(self) -> global___EncryptedClientIdentification: ...

    def __init__(self,
        *,
        ClientId : typing.Optional[global___ClientIdentification] = ...,
        ContentId : typing.Optional[global___LicenseRequestRaw.ContentIdentification] = ...,
        Type : typing.Optional[global___LicenseRequestRaw.RequestType.V] = ...,
        RequestTime : typing.Optional[builtins.int] = ...,
        KeyControlNonceDeprecated : typing.Optional[builtins.bytes] = ...,
        ProtocolVersion : typing.Optional[global___ProtocolVersion.V] = ...,
        KeyControlNonce : typing.Optional[builtins.int] = ...,
        EncryptedClientId : typing.Optional[global___EncryptedClientIdentification] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"ClientId",b"ClientId",u"ContentId",b"ContentId",u"EncryptedClientId",b"EncryptedClientId",u"KeyControlNonce",b"KeyControlNonce",u"KeyControlNonceDeprecated",b"KeyControlNonceDeprecated",u"ProtocolVersion",b"ProtocolVersion",u"RequestTime",b"RequestTime",u"Type",b"Type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"ClientId",b"ClientId",u"ContentId",b"ContentId",u"EncryptedClientId",b"EncryptedClientId",u"KeyControlNonce",b"KeyControlNonce",u"KeyControlNonceDeprecated",b"KeyControlNonceDeprecated",u"ProtocolVersion",b"ProtocolVersion",u"RequestTime",b"RequestTime",u"Type",b"Type"]) -> None: ...
global___LicenseRequestRaw = LicenseRequestRaw

class ProvisionedDeviceInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class WvSecurityLevel(metaclass=_WvSecurityLevel):
        V = typing.NewType('V', builtins.int)

    LEVEL_UNSPECIFIED = ProvisionedDeviceInfo.WvSecurityLevel.V(0)
    LEVEL_1 = ProvisionedDeviceInfo.WvSecurityLevel.V(1)
    LEVEL_2 = ProvisionedDeviceInfo.WvSecurityLevel.V(2)
    LEVEL_3 = ProvisionedDeviceInfo.WvSecurityLevel.V(3)

    class _WvSecurityLevel(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[WvSecurityLevel.V], builtins.type):  # type: ignore
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        LEVEL_UNSPECIFIED = ProvisionedDeviceInfo.WvSecurityLevel.V(0)
        LEVEL_1 = ProvisionedDeviceInfo.WvSecurityLevel.V(1)
        LEVEL_2 = ProvisionedDeviceInfo.WvSecurityLevel.V(2)
        LEVEL_3 = ProvisionedDeviceInfo.WvSecurityLevel.V(3)

    SYSTEMID_FIELD_NUMBER: builtins.int
    SOC_FIELD_NUMBER: builtins.int
    MANUFACTURER_FIELD_NUMBER: builtins.int
    MODEL_FIELD_NUMBER: builtins.int
    DEVICETYPE_FIELD_NUMBER: builtins.int
    MODELYEAR_FIELD_NUMBER: builtins.int
    SECURITYLEVEL_FIELD_NUMBER: builtins.int
    TESTDEVICE_FIELD_NUMBER: builtins.int
    SystemId: builtins.int = ...
    Soc: typing.Text = ...
    Manufacturer: typing.Text = ...
    Model: typing.Text = ...
    DeviceType: typing.Text = ...
    ModelYear: builtins.int = ...
    SecurityLevel: global___ProvisionedDeviceInfo.WvSecurityLevel.V = ...
    TestDevice: builtins.int = ...

    def __init__(self,
        *,
        SystemId : typing.Optional[builtins.int] = ...,
        Soc : typing.Optional[typing.Text] = ...,
        Manufacturer : typing.Optional[typing.Text] = ...,
        Model : typing.Optional[typing.Text] = ...,
        DeviceType : typing.Optional[typing.Text] = ...,
        ModelYear : typing.Optional[builtins.int] = ...,
        SecurityLevel : typing.Optional[global___ProvisionedDeviceInfo.WvSecurityLevel.V] = ...,
        TestDevice : typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"DeviceType",b"DeviceType",u"Manufacturer",b"Manufacturer",u"Model",b"Model",u"ModelYear",b"ModelYear",u"SecurityLevel",b"SecurityLevel",u"Soc",b"Soc",u"SystemId",b"SystemId",u"TestDevice",b"TestDevice"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"DeviceType",b"DeviceType",u"Manufacturer",b"Manufacturer",u"Model",b"Model",u"ModelYear",b"ModelYear",u"SecurityLevel",b"SecurityLevel",u"Soc",b"Soc",u"SystemId",b"SystemId",u"TestDevice",b"TestDevice"]) -> None: ...
global___ProvisionedDeviceInfo = ProvisionedDeviceInfo

class ProvisioningOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class CertificateType(metaclass=_CertificateType):
        V = typing.NewType('V', builtins.int)

    WIDEVINE_DRM = ProvisioningOptions.CertificateType.V(0)
    X509 = ProvisioningOptions.CertificateType.V(1)

    class _CertificateType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[CertificateType.V], builtins.type):  # type: ignore
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        WIDEVINE_DRM = ProvisioningOptions.CertificateType.V(0)
        X509 = ProvisioningOptions.CertificateType.V(1)

    CERTIFICATE_TYPE_FIELD_NUMBER: builtins.int
    CERTIFICATE_AUTHORITY_FIELD_NUMBER: builtins.int
    certificate_type: global___ProvisioningOptions.CertificateType.V = ...
    certificate_authority: typing.Text = ...

    def __init__(self,
        *,
        certificate_type : typing.Optional[global___ProvisioningOptions.CertificateType.V] = ...,
        certificate_authority : typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"certificate_authority",b"certificate_authority",u"certificate_type",b"certificate_type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"certificate_authority",b"certificate_authority",u"certificate_type",b"certificate_type"]) -> None: ...
global___ProvisioningOptions = ProvisioningOptions

class ProvisioningRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    CLIENT_ID_FIELD_NUMBER: builtins.int
    ENCRYPTED_CLIENT_ID_FIELD_NUMBER: builtins.int
    NONCE_FIELD_NUMBER: builtins.int
    OPTIONS_FIELD_NUMBER: builtins.int
    STABLE_ID_FIELD_NUMBER: builtins.int
    PROVIDER_ID_FIELD_NUMBER: builtins.int
    SPOID_FIELD_NUMBER: builtins.int
    nonce: builtins.bytes = ...
    stable_id: builtins.bytes = ...
    provider_id: builtins.bytes = ...
    spoid: builtins.bytes = ...

    @property
    def client_id(self) -> global___ClientIdentificationRaw: ...

    @property
    def encrypted_client_id(self) -> global___EncryptedClientIdentification: ...

    @property
    def options(self) -> global___ProvisioningOptions: ...

    def __init__(self,
        *,
        client_id : typing.Optional[global___ClientIdentificationRaw] = ...,
        encrypted_client_id : typing.Optional[global___EncryptedClientIdentification] = ...,
        nonce : typing.Optional[builtins.bytes] = ...,
        options : typing.Optional[global___ProvisioningOptions] = ...,
        stable_id : typing.Optional[builtins.bytes] = ...,
        provider_id : typing.Optional[builtins.bytes] = ...,
        spoid : typing.Optional[builtins.bytes] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"client_id",b"client_id",u"encrypted_client_id",b"encrypted_client_id",u"nonce",b"nonce",u"options",b"options",u"provider_id",b"provider_id",u"spoid",b"spoid",u"stable_id",b"stable_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"client_id",b"client_id",u"encrypted_client_id",b"encrypted_client_id",u"nonce",b"nonce",u"options",b"options",u"provider_id",b"provider_id",u"spoid",b"spoid",u"stable_id",b"stable_id"]) -> None: ...
global___ProvisioningRequest = ProvisioningRequest

class ProvisioningResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    DEVICE_RSA_KEY_FIELD_NUMBER: builtins.int
    DEVICE_RSA_KEY_IV_FIELD_NUMBER: builtins.int
    DEVICE_CERTIFICATE_FIELD_NUMBER: builtins.int
    NONCE_FIELD_NUMBER: builtins.int
    WRAPPING_KEY_FIELD_NUMBER: builtins.int
    device_rsa_key: builtins.bytes = ...
    device_rsa_key_iv: builtins.bytes = ...
    device_certificate: builtins.bytes = ...
    nonce: builtins.bytes = ...
    wrapping_key: builtins.bytes = ...

    def __init__(self,
        *,
        device_rsa_key : typing.Optional[builtins.bytes] = ...,
        device_rsa_key_iv : typing.Optional[builtins.bytes] = ...,
        device_certificate : typing.Optional[builtins.bytes] = ...,
        nonce : typing.Optional[builtins.bytes] = ...,
        wrapping_key : typing.Optional[builtins.bytes] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"device_certificate",b"device_certificate",u"device_rsa_key",b"device_rsa_key",u"device_rsa_key_iv",b"device_rsa_key_iv",u"nonce",b"nonce",u"wrapping_key",b"wrapping_key"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"device_certificate",b"device_certificate",u"device_rsa_key",b"device_rsa_key",u"device_rsa_key_iv",b"device_rsa_key_iv",u"nonce",b"nonce",u"wrapping_key",b"wrapping_key"]) -> None: ...
global___ProvisioningResponse = ProvisioningResponse

class RemoteAttestation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    CERTIFICATE_FIELD_NUMBER: builtins.int
    SALT_FIELD_NUMBER: builtins.int
    SIGNATURE_FIELD_NUMBER: builtins.int
    Salt: typing.Text = ...
    Signature: typing.Text = ...

    @property
    def Certificate(self) -> global___EncryptedClientIdentification: ...

    def __init__(self,
        *,
        Certificate : typing.Optional[global___EncryptedClientIdentification] = ...,
        Salt : typing.Optional[typing.Text] = ...,
        Signature : typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"Certificate",b"Certificate",u"Salt",b"Salt",u"Signature",b"Signature"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"Certificate",b"Certificate",u"Salt",b"Salt",u"Signature",b"Signature"]) -> None: ...
global___RemoteAttestation = RemoteAttestation

class SessionInit(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...

    def __init__(self,
        ) -> None: ...
global___SessionInit = SessionInit

class SessionState(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...

    def __init__(self,
        ) -> None: ...
global___SessionState = SessionState

class SignedCertificateStatusList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...

    def __init__(self,
        ) -> None: ...
global___SignedCertificateStatusList = SignedCertificateStatusList

class SignedDeviceCertificate(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    _DEVICECERTIFICATE_FIELD_NUMBER: builtins.int
    SIGNATURE_FIELD_NUMBER: builtins.int
    SIGNER_FIELD_NUMBER: builtins.int
    Signature: builtins.bytes = ...

    @property
    def _DeviceCertificate(self) -> global___DeviceCertificate: ...

    @property
    def Signer(self) -> global___SignedDeviceCertificate: ...

    def __init__(self,
        *,
        _DeviceCertificate : typing.Optional[global___DeviceCertificate] = ...,
        Signature : typing.Optional[builtins.bytes] = ...,
        Signer : typing.Optional[global___SignedDeviceCertificate] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"Signature",b"Signature",u"Signer",b"Signer",u"_DeviceCertificate",b"_DeviceCertificate"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"Signature",b"Signature",u"Signer",b"Signer",u"_DeviceCertificate",b"_DeviceCertificate"]) -> None: ...
global___SignedDeviceCertificate = SignedDeviceCertificate

class SignedProvisioningMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MESSAGE_FIELD_NUMBER: builtins.int
    SIGNATURE_FIELD_NUMBER: builtins.int
    PROTOCOL_VERSION_FIELD_NUMBER: builtins.int
    message: builtins.bytes = ...
    signature: builtins.bytes = ...
    protocol_version: global___ProtocolVersion.V = ...

    def __init__(self,
        *,
        message : typing.Optional[builtins.bytes] = ...,
        signature : typing.Optional[builtins.bytes] = ...,
        protocol_version : typing.Optional[global___ProtocolVersion.V] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"message",b"message",u"protocol_version",b"protocol_version",u"signature",b"signature"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"message",b"message",u"protocol_version",b"protocol_version",u"signature",b"signature"]) -> None: ...
global___SignedProvisioningMessage = SignedProvisioningMessage

class SignedMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class MessageType(metaclass=_MessageType):
        V = typing.NewType('V', builtins.int)

    LICENSE_REQUEST = SignedMessage.MessageType.V(1)
    LICENSE = SignedMessage.MessageType.V(2)
    ERROR_RESPONSE = SignedMessage.MessageType.V(3)
    SERVICE_CERTIFICATE_REQUEST = SignedMessage.MessageType.V(4)
    SERVICE_CERTIFICATE = SignedMessage.MessageType.V(5)

    class _MessageType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[MessageType.V], builtins.type):  # type: ignore
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        LICENSE_REQUEST = SignedMessage.MessageType.V(1)
        LICENSE = SignedMessage.MessageType.V(2)
        ERROR_RESPONSE = SignedMessage.MessageType.V(3)
        SERVICE_CERTIFICATE_REQUEST = SignedMessage.MessageType.V(4)
        SERVICE_CERTIFICATE = SignedMessage.MessageType.V(5)

    TYPE_FIELD_NUMBER: builtins.int
    MSG_FIELD_NUMBER: builtins.int
    SIGNATURE_FIELD_NUMBER: builtins.int
    SESSIONKEY_FIELD_NUMBER: builtins.int
    REMOTEATTESTATION_FIELD_NUMBER: builtins.int
    Type: global___SignedMessage.MessageType.V = ...
    Msg: builtins.bytes = ...
    Signature: builtins.bytes = ...
    SessionKey: builtins.bytes = ...

    @property
    def RemoteAttestation(self) -> global___RemoteAttestation: ...

    def __init__(self,
        *,
        Type : typing.Optional[global___SignedMessage.MessageType.V] = ...,
        Msg : typing.Optional[builtins.bytes] = ...,
        Signature : typing.Optional[builtins.bytes] = ...,
        SessionKey : typing.Optional[builtins.bytes] = ...,
        RemoteAttestation : typing.Optional[global___RemoteAttestation] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"Msg",b"Msg",u"RemoteAttestation",b"RemoteAttestation",u"SessionKey",b"SessionKey",u"Signature",b"Signature",u"Type",b"Type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"Msg",b"Msg",u"RemoteAttestation",b"RemoteAttestation",u"SessionKey",b"SessionKey",u"Signature",b"Signature",u"Type",b"Type"]) -> None: ...
global___SignedMessage = SignedMessage

class WidevineCencHeader(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class Algorithm(metaclass=_Algorithm):
        V = typing.NewType('V', builtins.int)

    UNENCRYPTED = WidevineCencHeader.Algorithm.V(0)
    AESCTR = WidevineCencHeader.Algorithm.V(1)

    class _Algorithm(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Algorithm.V], builtins.type):  # type: ignore
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        UNENCRYPTED = WidevineCencHeader.Algorithm.V(0)
        AESCTR = WidevineCencHeader.Algorithm.V(1)

    ALGORITHM_FIELD_NUMBER: builtins.int
    KEY_ID_FIELD_NUMBER: builtins.int
    PROVIDER_FIELD_NUMBER: builtins.int
    CONTENT_ID_FIELD_NUMBER: builtins.int
    TRACK_TYPE_DEPRECATED_FIELD_NUMBER: builtins.int
    POLICY_FIELD_NUMBER: builtins.int
    CRYPTO_PERIOD_INDEX_FIELD_NUMBER: builtins.int
    GROUPED_LICENSE_FIELD_NUMBER: builtins.int
    PROTECTION_SCHEME_FIELD_NUMBER: builtins.int
    CRYPTO_PERIOD_SECONDS_FIELD_NUMBER: builtins.int
    algorithm: global___WidevineCencHeader.Algorithm.V = ...

    @property
    def key_id(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    provider: typing.Text = ...
    content_id: builtins.bytes = ...
    track_type_deprecated: typing.Text = ...
    policy: typing.Text = ...
    crypto_period_index: builtins.int = ...
    grouped_license: builtins.bytes = ...
    protection_scheme: builtins.int = ...
    crypto_period_seconds: builtins.int = ...

    def __init__(self,
        *,
        algorithm : typing.Optional[global___WidevineCencHeader.Algorithm.V] = ...,
        key_id : typing.Optional[typing.Iterable[builtins.bytes]] = ...,
        provider : typing.Optional[typing.Text] = ...,
        content_id : typing.Optional[builtins.bytes] = ...,
        track_type_deprecated : typing.Optional[typing.Text] = ...,
        policy : typing.Optional[typing.Text] = ...,
        crypto_period_index : typing.Optional[builtins.int] = ...,
        grouped_license : typing.Optional[builtins.bytes] = ...,
        protection_scheme : typing.Optional[builtins.int] = ...,
        crypto_period_seconds : typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"algorithm",b"algorithm",u"content_id",b"content_id",u"crypto_period_index",b"crypto_period_index",u"crypto_period_seconds",b"crypto_period_seconds",u"grouped_license",b"grouped_license",u"policy",b"policy",u"protection_scheme",b"protection_scheme",u"provider",b"provider",u"track_type_deprecated",b"track_type_deprecated"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"algorithm",b"algorithm",u"content_id",b"content_id",u"crypto_period_index",b"crypto_period_index",u"crypto_period_seconds",b"crypto_period_seconds",u"grouped_license",b"grouped_license",u"key_id",b"key_id",u"policy",b"policy",u"protection_scheme",b"protection_scheme",u"provider",b"provider",u"track_type_deprecated",b"track_type_deprecated"]) -> None: ...
global___WidevineCencHeader = WidevineCencHeader

class SignedLicenseRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class MessageType(metaclass=_MessageType):
        V = typing.NewType('V', builtins.int)

    LICENSE_REQUEST = SignedLicenseRequest.MessageType.V(1)
    LICENSE = SignedLicenseRequest.MessageType.V(2)
    ERROR_RESPONSE = SignedLicenseRequest.MessageType.V(3)
    SERVICE_CERTIFICATE_REQUEST = SignedLicenseRequest.MessageType.V(4)
    SERVICE_CERTIFICATE = SignedLicenseRequest.MessageType.V(5)

    class _MessageType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[MessageType.V], builtins.type):  # type: ignore
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        LICENSE_REQUEST = SignedLicenseRequest.MessageType.V(1)
        LICENSE = SignedLicenseRequest.MessageType.V(2)
        ERROR_RESPONSE = SignedLicenseRequest.MessageType.V(3)
        SERVICE_CERTIFICATE_REQUEST = SignedLicenseRequest.MessageType.V(4)
        SERVICE_CERTIFICATE = SignedLicenseRequest.MessageType.V(5)

    TYPE_FIELD_NUMBER: builtins.int
    MSG_FIELD_NUMBER: builtins.int
    SIGNATURE_FIELD_NUMBER: builtins.int
    SESSIONKEY_FIELD_NUMBER: builtins.int
    REMOTEATTESTATION_FIELD_NUMBER: builtins.int
    Type: global___SignedLicenseRequest.MessageType.V = ...
    Signature: builtins.bytes = ...
    SessionKey: builtins.bytes = ...

    @property
    def Msg(self) -> global___LicenseRequest: ...

    @property
    def RemoteAttestation(self) -> global___RemoteAttestation: ...

    def __init__(self,
        *,
        Type : typing.Optional[global___SignedLicenseRequest.MessageType.V] = ...,
        Msg : typing.Optional[global___LicenseRequest] = ...,
        Signature : typing.Optional[builtins.bytes] = ...,
        SessionKey : typing.Optional[builtins.bytes] = ...,
        RemoteAttestation : typing.Optional[global___RemoteAttestation] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"Msg",b"Msg",u"RemoteAttestation",b"RemoteAttestation",u"SessionKey",b"SessionKey",u"Signature",b"Signature",u"Type",b"Type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"Msg",b"Msg",u"RemoteAttestation",b"RemoteAttestation",u"SessionKey",b"SessionKey",u"Signature",b"Signature",u"Type",b"Type"]) -> None: ...
global___SignedLicenseRequest = SignedLicenseRequest

class SignedLicenseRequestRaw(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class MessageType(metaclass=_MessageType):
        V = typing.NewType('V', builtins.int)

    LICENSE_REQUEST = SignedLicenseRequestRaw.MessageType.V(1)
    LICENSE = SignedLicenseRequestRaw.MessageType.V(2)
    ERROR_RESPONSE = SignedLicenseRequestRaw.MessageType.V(3)
    SERVICE_CERTIFICATE_REQUEST = SignedLicenseRequestRaw.MessageType.V(4)
    SERVICE_CERTIFICATE = SignedLicenseRequestRaw.MessageType.V(5)

    class _MessageType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[MessageType.V], builtins.type):  # type: ignore
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        LICENSE_REQUEST = SignedLicenseRequestRaw.MessageType.V(1)
        LICENSE = SignedLicenseRequestRaw.MessageType.V(2)
        ERROR_RESPONSE = SignedLicenseRequestRaw.MessageType.V(3)
        SERVICE_CERTIFICATE_REQUEST = SignedLicenseRequestRaw.MessageType.V(4)
        SERVICE_CERTIFICATE = SignedLicenseRequestRaw.MessageType.V(5)

    TYPE_FIELD_NUMBER: builtins.int
    MSG_FIELD_NUMBER: builtins.int
    SIGNATURE_FIELD_NUMBER: builtins.int
    SESSIONKEY_FIELD_NUMBER: builtins.int
    REMOTEATTESTATION_FIELD_NUMBER: builtins.int
    Type: global___SignedLicenseRequestRaw.MessageType.V = ...
    Signature: builtins.bytes = ...
    SessionKey: builtins.bytes = ...

    @property
    def Msg(self) -> global___LicenseRequestRaw: ...

    @property
    def RemoteAttestation(self) -> global___RemoteAttestation: ...

    def __init__(self,
        *,
        Type : typing.Optional[global___SignedLicenseRequestRaw.MessageType.V] = ...,
        Msg : typing.Optional[global___LicenseRequestRaw] = ...,
        Signature : typing.Optional[builtins.bytes] = ...,
        SessionKey : typing.Optional[builtins.bytes] = ...,
        RemoteAttestation : typing.Optional[global___RemoteAttestation] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"Msg",b"Msg",u"RemoteAttestation",b"RemoteAttestation",u"SessionKey",b"SessionKey",u"Signature",b"Signature",u"Type",b"Type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"Msg",b"Msg",u"RemoteAttestation",b"RemoteAttestation",u"SessionKey",b"SessionKey",u"Signature",b"Signature",u"Type",b"Type"]) -> None: ...
global___SignedLicenseRequestRaw = SignedLicenseRequestRaw

class SignedLicense(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class MessageType(metaclass=_MessageType):
        V = typing.NewType('V', builtins.int)

    LICENSE_REQUEST = SignedLicense.MessageType.V(1)
    LICENSE = SignedLicense.MessageType.V(2)
    ERROR_RESPONSE = SignedLicense.MessageType.V(3)
    SERVICE_CERTIFICATE_REQUEST = SignedLicense.MessageType.V(4)
    SERVICE_CERTIFICATE = SignedLicense.MessageType.V(5)

    class _MessageType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[MessageType.V], builtins.type):  # type: ignore
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        LICENSE_REQUEST = SignedLicense.MessageType.V(1)
        LICENSE = SignedLicense.MessageType.V(2)
        ERROR_RESPONSE = SignedLicense.MessageType.V(3)
        SERVICE_CERTIFICATE_REQUEST = SignedLicense.MessageType.V(4)
        SERVICE_CERTIFICATE = SignedLicense.MessageType.V(5)

    TYPE_FIELD_NUMBER: builtins.int
    MSG_FIELD_NUMBER: builtins.int
    SIGNATURE_FIELD_NUMBER: builtins.int
    SESSIONKEY_FIELD_NUMBER: builtins.int
    REMOTEATTESTATION_FIELD_NUMBER: builtins.int
    Type: global___SignedLicense.MessageType.V = ...
    Signature: builtins.bytes = ...
    SessionKey: builtins.bytes = ...

    @property
    def Msg(self) -> global___License: ...

    @property
    def RemoteAttestation(self) -> global___RemoteAttestation: ...

    def __init__(self,
        *,
        Type : typing.Optional[global___SignedLicense.MessageType.V] = ...,
        Msg : typing.Optional[global___License] = ...,
        Signature : typing.Optional[builtins.bytes] = ...,
        SessionKey : typing.Optional[builtins.bytes] = ...,
        RemoteAttestation : typing.Optional[global___RemoteAttestation] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"Msg",b"Msg",u"RemoteAttestation",b"RemoteAttestation",u"SessionKey",b"SessionKey",u"Signature",b"Signature",u"Type",b"Type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"Msg",b"Msg",u"RemoteAttestation",b"RemoteAttestation",u"SessionKey",b"SessionKey",u"Signature",b"Signature",u"Type",b"Type"]) -> None: ...
global___SignedLicense = SignedLicense

class SignedServiceCertificate(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class MessageType(metaclass=_MessageType):
        V = typing.NewType('V', builtins.int)

    LICENSE_REQUEST = SignedServiceCertificate.MessageType.V(1)
    LICENSE = SignedServiceCertificate.MessageType.V(2)
    ERROR_RESPONSE = SignedServiceCertificate.MessageType.V(3)
    SERVICE_CERTIFICATE_REQUEST = SignedServiceCertificate.MessageType.V(4)
    SERVICE_CERTIFICATE = SignedServiceCertificate.MessageType.V(5)

    class _MessageType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[MessageType.V], builtins.type):  # type: ignore
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        LICENSE_REQUEST = SignedServiceCertificate.MessageType.V(1)
        LICENSE = SignedServiceCertificate.MessageType.V(2)
        ERROR_RESPONSE = SignedServiceCertificate.MessageType.V(3)
        SERVICE_CERTIFICATE_REQUEST = SignedServiceCertificate.MessageType.V(4)
        SERVICE_CERTIFICATE = SignedServiceCertificate.MessageType.V(5)

    TYPE_FIELD_NUMBER: builtins.int
    MSG_FIELD_NUMBER: builtins.int
    SIGNATURE_FIELD_NUMBER: builtins.int
    SESSIONKEY_FIELD_NUMBER: builtins.int
    REMOTEATTESTATION_FIELD_NUMBER: builtins.int
    Type: global___SignedServiceCertificate.MessageType.V = ...
    Signature: builtins.bytes = ...
    SessionKey: builtins.bytes = ...

    @property
    def Msg(self) -> global___SignedDeviceCertificate: ...

    @property
    def RemoteAttestation(self) -> global___RemoteAttestation: ...

    def __init__(self,
        *,
        Type : typing.Optional[global___SignedServiceCertificate.MessageType.V] = ...,
        Msg : typing.Optional[global___SignedDeviceCertificate] = ...,
        Signature : typing.Optional[builtins.bytes] = ...,
        SessionKey : typing.Optional[builtins.bytes] = ...,
        RemoteAttestation : typing.Optional[global___RemoteAttestation] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"Msg",b"Msg",u"RemoteAttestation",b"RemoteAttestation",u"SessionKey",b"SessionKey",u"Signature",b"Signature",u"Type",b"Type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"Msg",b"Msg",u"RemoteAttestation",b"RemoteAttestation",u"SessionKey",b"SessionKey",u"Signature",b"Signature",u"Type",b"Type"]) -> None: ...
global___SignedServiceCertificate = SignedServiceCertificate

class FileHashes(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class Signature(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        FILENAME_FIELD_NUMBER: builtins.int
        TEST_SIGNING_FIELD_NUMBER: builtins.int
        SHA512HASH_FIELD_NUMBER: builtins.int
        MAIN_EXE_FIELD_NUMBER: builtins.int
        SIGNATURE_FIELD_NUMBER: builtins.int
        filename: typing.Text = ...
        test_signing: builtins.bool = ...
        SHA512Hash: builtins.bytes = ...
        main_exe: builtins.bool = ...
        signature: builtins.bytes = ...

        def __init__(self,
            *,
            filename : typing.Optional[typing.Text] = ...,
            test_signing : typing.Optional[builtins.bool] = ...,
            SHA512Hash : typing.Optional[builtins.bytes] = ...,
            main_exe : typing.Optional[builtins.bool] = ...,
            signature : typing.Optional[builtins.bytes] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal[u"SHA512Hash",b"SHA512Hash",u"filename",b"filename",u"main_exe",b"main_exe",u"signature",b"signature",u"test_signing",b"test_signing"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"SHA512Hash",b"SHA512Hash",u"filename",b"filename",u"main_exe",b"main_exe",u"signature",b"signature",u"test_signing",b"test_signing"]) -> None: ...

    SIGNER_FIELD_NUMBER: builtins.int
    SIGNATURES_FIELD_NUMBER: builtins.int
    signer: builtins.bytes = ...

    @property
    def signatures(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FileHashes.Signature]: ...

    def __init__(self,
        *,
        signer : typing.Optional[builtins.bytes] = ...,
        signatures : typing.Optional[typing.Iterable[global___FileHashes.Signature]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"signer",b"signer"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"signatures",b"signatures",u"signer",b"signer"]) -> None: ...
global___FileHashes = FileHashes
